const kitchenPlanning = [
  {
    title: "Start with the full wall",
    text: "Wide photos help show cabinet lines, counters, corners, windows, outlets, and the main focal area before layout is discussed.",
  },
  {
    title: "Compare the pattern to the openings",
    text: "Tile size and pattern affect where cuts land around outlets, cabinet ends, windows, and the space behind a range or sink.",
  },
  {
    title: "Confirm the finish choices",
    text: "Share the exact product, intended pattern, grout preference, and any exposed-edge condition so the visible details can be planned together.",
  },
];

const bathroomPlanning = [
  {
    title: "Photograph the whole enclosure",
    text: "Include the tub or shower, every wall, the floor, plumbing locations, openings, niches, and the transition to the rest of the room.",
  },
  {
    title: "Identify focal surfaces",
    text: "If a pattern or contrasting surface is planned, note where it should begin and end and which view should feel most balanced when the room is entered.",
  },
  {
    title: "Confirm the actual products",
    text: "Wall, floor, trim, grout, fixtures, and substrate conditions all affect planning. Product names and photos are more reliable than appearance alone.",
  },
];

const floorPlanning = [
  {
    title: "Show the room edges",
    text: "Photograph the full room plus doorways, closets, baseboards, vents, and every transition to an adjoining surface.",
  },
  {
    title: "Share the exact flooring",
    text: "A product label or link confirms the material, plank or tile dimensions, installation requirements, and intended direction.",
  },
  {
    title: "Discuss layout and transitions",
    text: "Room shape, starting line, repeated pattern, perimeter cuts, and finished heights all influence the final layout.",
  },
];

const featureWallPlanning = [
  {
    title: "Define the visible boundary",
    text: "Show the full wall, ceiling line, floor line, adjacent openings, furniture, and any outlets or fixtures that meet the feature surface.",
  },
  {
    title: "Confirm the selected product",
    text: "Share the manufacturer, product name, dimensions, finish, and installation instructions instead of relying on appearance in a photo.",
  },
  {
    title: "Plan the composition",
    text: "Panel rhythm, mixed tones, edge treatment, and the relationship to nearby woodwork or cabinetry should be considered as one elevation.",
  },
];

export const projects = [
  {
    slug: "pale-blue-arabesque-kitchen",
    indexable: true,
    editorialStatus: "publish",
    title: "Arabesque Kitchen Backsplash",
    seoTitle: "Arabesque Kitchen Backsplash Project | Mr. Backsplash",
    description: "See a finished white arabesque-pattern backsplash framed by pale blue cabinets, with practical planning notes for range walls, outlets, and cabinet edges.",
    summary: "A reflective white arabesque pattern creates a focused range wall between pale blue cabinets and a white hood.",
    category: "Kitchen backsplash",
    stage: "Finished view",
    image: {
      stem: "pale-blue-arabesque-kitchen",
      alt: "White arabesque-pattern backsplash behind a range, framed by pale blue cabinets and a white hood",
      width: 1600,
      height: 2133,
      position: "center 55%",
    },
    caption: "The photo shows the finished range wall and the backsplash continuing beneath the cabinets on both sides.",
    observations: [
      { title: "A centered focal field", text: "The arabesque repeat is most prominent directly below the hood and behind the range." },
      { title: "Several fixed edges", text: "The visible surface meets upper cabinets, counters, the hood, the range, and two outlets." },
      { title: "A restrained palette", text: "Reflective white shapes contrast with pale blue cabinetry and warm-metal hardware." },
    ],
    planning: kitchenPlanning,
    service: { href: "/services/kitchen-backsplash-installation/", label: "Kitchen backsplash service" },
    advice: { href: "/advice/planning-a-kitchen-backsplash/", label: "Kitchen backsplash planning guide" },
  },
  {
    slug: "white-subway-kitchen",
    indexable: true,
    editorialStatus: "publish",
    title: "Gloss White Subway Kitchen",
    seoTitle: "Gloss White Subway Kitchen Project | Mr. Backsplash",
    description: "Explore a gloss white rectangular-tile backsplash wrapping a bright kitchen with wood counters, plus planning guidance for corners, windows, and outlets.",
    summary: "A continuous field of gloss white rectangular tile follows a wide kitchen around corners, a sink window, and a range wall.",
    category: "Kitchen backsplash",
    stage: "Finished view",
    image: {
      stem: "white-subway-kitchen",
      alt: "Wide kitchen with a gloss white rectangular-tile backsplash between white cabinets and wood counters",
      width: 1600,
      height: 1200,
      position: "center center",
    },
    caption: "This wide view shows the backsplash continuing around the worktop walls and beneath the upper cabinets.",
    observations: [
      { title: "A long visual run", text: "The same horizontal pattern continues across multiple walls rather than stopping at one focal area." },
      { title: "Windows and corners", text: "The installation meets a double window, inside corners, cabinet ends, outlets, and the range area." },
      { title: "Surface contrast", text: "Gloss white tile sits between light cabinetry and warm wood counters." },
    ],
    planning: kitchenPlanning,
    service: { href: "/services/kitchen-backsplash-installation/", label: "Kitchen backsplash service" },
    advice: { href: "/advice/planning-a-kitchen-backsplash/", label: "Kitchen backsplash planning guide" },
  },
  {
    slug: "herringbone-feature-shower",
    indexable: true,
    editorialStatus: "publish",
    title: "Herringbone Feature Shower",
    seoTitle: "Herringbone Feature Shower Project | Mr. Backsplash",
    description: "See a glass shower with a gray herringbone feature wall, white side walls, and a small-format floor, with practical shower-tile planning guidance.",
    summary: "A gray herringbone field anchors the back wall of a glass shower while white rectangular side walls keep the contrast clear.",
    category: "Bathroom and shower tile",
    stage: "Finished view",
    image: {
      stem: "herringbone-glass-shower",
      alt: "Glass shower with a gray herringbone feature wall, white rectangular side-wall tile, and small round floor tile",
      width: 1600,
      height: 2133,
      position: "center center",
    },
    caption: "The straight-on view shows the feature wall, side walls, floor, niche, fixtures, curb, and glass enclosure together.",
    observations: [
      { title: "One clear focal wall", text: "The darker herringbone field fills the back wall from the shower floor to its upper edge." },
      { title: "Pattern transitions", text: "The feature surface meets white rectangular side walls and a small round floor surface." },
      { title: "Visible functional details", text: "The photo includes a niche, shower head, control, drain, curb, and glass hardware." },
    ],
    planning: bathroomPlanning,
    service: { href: "/services/bathroom-shower-tile/", label: "Bathroom and shower tile service" },
    advice: { href: "/advice/planning-bathroom-shower-tile/", label: "Bathroom and shower planning guide" },
  },
  {
    slug: "patterned-bathroom-floor",
    indexable: true,
    editorialStatus: "publish",
    title: "Patterned Bathroom Floor",
    seoTitle: "Patterned Bathroom Tile Floor Project | Mr. Backsplash",
    description: "See a gray-and-white patterned bathroom floor carried from the doorway toward the tub, with planning notes for motif alignment, edges, and transitions.",
    summary: "A repeating gray-and-white motif carries across the bathroom floor from the wood threshold toward the tub and vanity.",
    category: "Tile flooring",
    stage: "Finished view",
    image: {
      stem: "patterned-bathroom-floor",
      alt: "Gray-and-white patterned bathroom tile floor extending from a wood threshold toward a tub and green vanity",
      width: 1600,
      height: 2133,
      position: "center 72%",
    },
    caption: "The doorway view makes the repeated floor motif, grout grid, perimeter cuts, and threshold transition easy to compare.",
    observations: [
      { title: "A repeated motif", text: "Four-tile groupings form a larger continuous pattern across the visible floor." },
      { title: "Several perimeter conditions", text: "The floor meets a wood threshold, walls, a tub apron, a toilet, and a freestanding vanity." },
      { title: "A deliberate contrast", text: "The gray-and-white floor pattern sits beside muted walls and a deep green cabinet." },
    ],
    planning: floorPlanning,
    service: { href: "/services/tile-floor-installation/", label: "Tile floor installation service" },
    advice: { href: "/advice/preparing-for-tile-flooring-installation/", label: "Tile flooring preparation guide" },
  },
  {
    slug: "wood-look-plank-floor",
    indexable: true,
    editorialStatus: "publish",
    title: "Dark Wood-Look Plank Floor",
    seoTitle: "Dark Wood-Look Plank Flooring Project | Mr. Backsplash",
    description: "See a finished dark wood-look plank floor across a bright room, with practical guidance for product confirmation, plank direction, edges, and transitions.",
    summary: "A dark wood-look plank surface runs through a bright room and into a small adjoining opening. The exact flooring product is not identified.",
    category: "Flooring installation",
    stage: "Finished view",
    image: {
      stem: "wood-look-plank-floor",
      alt: "Dark wood-look plank floor running across a bright room with white trim and a partial wood-paneled wall",
      width: 1600,
      height: 2133,
      position: "center 72%",
    },
    caption: "The room view shows plank direction, staggered joints, perimeter edges, a doorway, and a second opening without identifying the product material.",
    observations: [
      { title: "One continuous direction", text: "The planks run lengthwise across the room and continue through the visible opening." },
      { title: "Staggered end joints", text: "Short and long board visuals alternate rather than forming a repeated grid." },
      { title: "Several finish edges", text: "The floor meets white base trim, a paneled wall, a doorway, and an open passage." },
    ],
    planning: floorPlanning,
    service: { href: "/services/laminate-flooring/", label: "Laminate flooring service" },
    advice: { href: "/advice/preparing-for-tile-flooring-installation/", label: "Flooring preparation guide" },
  },
  {
    slug: "stone-feature-wall",
    indexable: true,
    editorialStatus: "publish",
    title: "Multitone Feature Wall",
    seoTitle: "Multitone Interior Feature Wall Project | Mr. Backsplash",
    description: "Explore a full-height multitone feature surface behind a wood cabinet, with practical planning notes for panel rhythm, boundaries, and nearby woodwork.",
    summary: "A multitone, stacked-format surface fills the wall between two wood-trimmed openings and rises behind a freestanding cabinet.",
    category: "Specialty surface installation",
    stage: "Finished view",
    image: {
      stem: "stone-feature-wall",
      alt: "Full-height multitone stacked-format feature wall between wood-trimmed openings and behind a wood cabinet",
      width: 1600,
      height: 2133,
      position: "center center",
    },
    caption: "The straight-on photo shows the full feature surface, its side trim, top boundary, floor line, and relationship to the cabinet.",
    observations: [
      { title: "A full-height composition", text: "The stacked-format field spans from the floor area to the wood trim at the ceiling." },
      { title: "Mixed sizes and tones", text: "Rectangular pieces vary in width and move through warm brown, gray, and light neutral colors." },
      { title: "Framed by existing woodwork", text: "Vertical trim and adjacent openings define the left and right boundaries of the feature wall." },
    ],
    planning: featureWallPlanning,
    service: { href: "/services/", label: "View Mr. Backsplash services" },
    advice: { href: "/advice/photos-details-for-tile-estimate/", label: "Photo and estimate guide" },
  },
  {
    slug: "modern-hex-kitchen",
    indexable: true,
    editorialStatus: "publish",
    title: "Gray and White Hex Mosaic Kitchen",
    seoTitle: "Hex Mosaic Kitchen Backsplash Project | Mr. Backsplash",
    description: "See the same kitchen before installation, during hex-tile layout, and after the gray-and-white mosaic backsplash was finished.",
    summary: "One kitchen is shown before installation, during layout, and after the gray-and-white hex backsplash was complete.",
    category: "Kitchen backsplash",
    stage: "Before, progress and finished",
    image: { stem: "modern-hex-kitchen", alt: "Kitchen with a gray-and-white hex-pattern backsplash around a range, corner sink, windows, and outlets", width: 1600, height: 1200, position: "center center" },
    caption: "The finished wide view shows the patterned field across the range wall, sink corner, windows, and outlets.",
    gallery: [
      {
        stem: "modern-hex-kitchen-before",
        label: "Before",
        alt: "The same white-and-gray kitchen before the hex backsplash was installed",
        width: 540,
        height: 720,
        position: "center center",
        caption: "Before installation, the counter walls were painted gray between the white cabinets, corner windows, and black range hood.",
      },
      {
        stem: "modern-hex-kitchen-progress",
        label: "In progress",
        alt: "Close view of gray-and-white hex tile being laid beneath the kitchen window",
        width: 960,
        height: 720,
        position: "center center",
        caption: "A low progress view shows the individual hex pieces being fitted beneath the window ledge.",
      },
      {
        stem: "modern-hex-kitchen-range-detail",
        label: "Finished detail",
        alt: "Finished gray-and-white hex mosaic backsplash behind the kitchen range",
        width: 960,
        height: 720,
        position: "center center",
        caption: "The finished range wall shows the hex pattern meeting the hood, outlets, window trim, counters, and cabinet edges.",
      },
    ],
    observations: [
      { title: "One room across every stage", text: "The cabinets, corner windows, range, hood, island, and surrounding walls match from the first photo through the finished view." },
      { title: "A connected pattern", text: "Light, medium, and dark hex shapes continue from the range wall through the sink corner and beneath the windows." },
      { title: "Detailed boundaries", text: "The finished field meets outlets, switches, cabinet ends, window trim, the hood, and both counter runs." },
    ],
    planning: kitchenPlanning,
    service: { href: "/services/kitchen-backsplash-installation/", label: "Kitchen backsplash service" },
    advice: { href: "/advice/planning-a-kitchen-backsplash/", label: "Kitchen backsplash planning guide" },
  },
  {
    slug: "diamond-mosaic-kitchen",
    indexable: false,
    editorialStatus: "hold-for-facts",
    title: "Diamond-Pattern Mosaic Kitchen",
    seoTitle: "Diamond-Pattern Mosaic Kitchen | Mr. Backsplash",
    description: "View a light diamond-pattern mosaic backsplash spanning a kitchen range, sink, window, outlets, and cabinet edges.",
    summary: "A light diamond-pattern mosaic with dark intersections runs across the counter wall and beneath a window.",
    category: "Kitchen backsplash",
    stage: "Finished view",
    image: { stem: "diamond-mosaic-kitchen", alt: "Kitchen with a light diamond-pattern mosaic backsplash, dark cabinets, a range, sink, and window", width: 1600, height: 1200, position: "center center" },
    caption: "The photo shows how the repeat meets the range, window casing, outlets, sink wall, and tall cabinet.",
    observations: [
      { title: "A small repeating shape", text: "Light diamond forms are connected by dark points across the backsplash field." },
      { title: "A window-centered run", text: "The pattern continues below and to both sides of the window." },
      { title: "Strong surrounding contrast", text: "The light field sits between dark lower cabinets, wood upper cabinets, and a light counter." },
    ],
    planning: kitchenPlanning,
    service: { href: "/services/kitchen-backsplash-installation/", label: "Kitchen backsplash service" },
    advice: { href: "/advice/planning-a-kitchen-backsplash/", label: "Kitchen backsplash planning guide" },
  },
  {
    slug: "classic-white-subway-kitchen",
    indexable: false,
    editorialStatus: "hold-for-facts",
    title: "Classic White Subway Kitchen",
    seoTitle: "Classic White Subway Kitchen | Mr. Backsplash",
    description: "View a white rectangular-tile backsplash wrapping a kitchen with wood cabinets, dark counters, windows, outlets, and a range wall.",
    summary: "A white horizontal running pattern creates a bright band between wood cabinetry and dark counters around a large kitchen.",
    category: "Kitchen backsplash",
    stage: "Finished view",
    image: { stem: "classic-subway-kitchen", alt: "Large kitchen with wood cabinets, dark counters, and a white rectangular-tile backsplash", width: 1600, height: 1785, position: "center center" },
    caption: "The wide view shows the backsplash continuing behind the sink and range and around several cabinet sections.",
    observations: [
      { title: "A consistent horizontal band", text: "White rectangular shapes run between the counters and cabinets across the visible walls." },
      { title: "Several focal points", text: "The installation passes the sink window, range, microwave, outlets, and open cabinet ends." },
      { title: "High light-and-dark contrast", text: "The light backsplash separates warm wood cabinets from black counters." },
    ],
    planning: kitchenPlanning,
    service: { href: "/services/kitchen-backsplash-installation/", label: "Kitchen backsplash service" },
    advice: { href: "/advice/planning-a-kitchen-backsplash/", label: "Kitchen backsplash planning guide" },
  },
  {
    slug: "brass-kitchen-detail",
    indexable: false,
    editorialStatus: "hold-for-facts",
    title: "Arabesque Range-Wall Detail",
    seoTitle: "Arabesque Range-Wall Detail | Mr. Backsplash",
    description: "View a close range-wall detail with a white arabesque pattern, pale blue cabinets, and warm-metal fixtures.",
    summary: "A close view isolates the arabesque repeat between the range, hood, side cabinets, and a warm-metal faucet.",
    category: "Kitchen finish detail",
    stage: "Finished detail",
    image: { stem: "brass-kitchen-detail", alt: "Close view of a white arabesque-pattern range wall with pale blue cabinets and warm-metal fixtures", width: 1600, height: 2133, position: "center 45%" },
    caption: "This detail photo is presented independently because the repository does not confirm which wider project view belongs with it.",
    observations: [
      { title: "A tight focal composition", text: "The image centers the range wall below the hood and between two cabinet edges." },
      { title: "Visible pattern boundaries", text: "The repeat ends at the counters, range, hood, and adjacent cabinet sides." },
      { title: "Warm and cool finishes", text: "Warm-metal fixtures stand in front of pale blue cabinetry and a white reflective field." },
    ],
    planning: kitchenPlanning,
    service: { href: "/services/kitchen-backsplash-installation/", label: "Kitchen backsplash service" },
    advice: { href: "/advice/planning-a-kitchen-backsplash/", label: "Kitchen backsplash planning guide" },
  },
  {
    slug: "freestanding-tub-tile",
    indexable: false,
    editorialStatus: "hold-for-facts",
    title: "Freestanding Tub Tile Detail",
    seoTitle: "Freestanding Tub Tile Detail | Mr. Backsplash",
    description: "View a freestanding tub bordered by large light wall pieces and a small white floor pattern, with planning notes for edges and fixtures.",
    summary: "A freestanding tub sits within a light tiled area bordered by large wall pieces, a small-format floor, and warm-metal fixtures.",
    category: "Bathroom tile",
    stage: "Finished view",
    image: { stem: "freestanding-tub-tile", alt: "Freestanding white tub with large light wall tile, small white floor tile, and warm-metal fixtures", width: 1600, height: 1200, position: "center center" },
    caption: "The centered photo shows wall and floor surfaces meeting around the tub and freestanding fixture.",
    observations: [
      { title: "Two visible surface scales", text: "Large light wall pieces meet a much smaller repeating floor surface." },
      { title: "A centered fixture", text: "The tub and freestanding faucet define the middle of the composition." },
      { title: "Several open edges", text: "Wall pieces stop below painted walls and finish vertically at both sides." },
    ],
    planning: bathroomPlanning,
    service: { href: "/services/bathroom-shower-tile/", label: "Bathroom and shower tile service" },
    advice: { href: "/advice/planning-bathroom-shower-tile/", label: "Bathroom and shower planning guide" },
  },
  {
    slug: "marble-look-tub-surround",
    indexable: false,
    editorialStatus: "hold-for-facts",
    title: "Marble-Look Tub Surround",
    seoTitle: "Marble-Look Tub Surround Detail | Mr. Backsplash",
    description: "View an in-progress tub surround with marble-look rectangular tile and a built-in wall niche, plus practical planning guidance.",
    summary: "An in-progress tub surround uses marble-look rectangular tile across three walls with a built-in niche on the right.",
    category: "Bathroom tile",
    stage: "In-progress view",
    image: { stem: "marble-look-tub-surround", alt: "In-progress tub surround with marble-look rectangular tile across three walls and a built-in niche", width: 1600, height: 2133, position: "center center" },
    caption: "The image is clearly an in-progress view; open perimeter edges and unfinished fixture openings remain visible.",
    observations: [
      { title: "A three-wall running pattern", text: "Rectangular pieces continue from the back wall onto both side walls." },
      { title: "A built-in niche", text: "The right wall includes a recessed shelf within the surrounding pattern." },
      { title: "Work still in progress", text: "Open edges, fixture openings, and surrounding wall areas show that this is not a final-room photo." },
    ],
    planning: bathroomPlanning,
    service: { href: "/services/bathroom-shower-tile/", label: "Bathroom and shower tile service" },
    advice: { href: "/advice/planning-bathroom-shower-tile/", label: "Bathroom and shower planning guide" },
  },
  {
    slug: "light-tile-floor",
    indexable: true,
    editorialStatus: "publish",
    title: "Wood-Paneled Room Tile Floor",
    seoTitle: "Wood-Paneled Room Tile Floor Project | Mr. Backsplash",
    description: "See the same wood-paneled room during floor preparation and after a light square-format tile floor was completed.",
    summary: "The same wood-paneled room is shown with its original floor, prepared underlayment, and completed light square tile.",
    category: "Tile flooring",
    stage: "Before, preparation and finished",
    image: { stem: "light-tile-floor", alt: "Light square-format tile floor in a compact room with wood-paneled walls, a doorway, and windows", width: 1600, height: 2133, position: "center 72%" },
    caption: "The finished doorway view shows the square grid, perimeter cuts, wall edges, and transitions in the completed room.",
    gallery: [
      {
        stem: "light-tile-floor-before",
        label: "Before and early prep",
        alt: "Wood-paneled room with the original floor exposed and the first section of underlayment in place",
        width: 1600,
        height: 2133,
        position: "center center",
        caption: "The first view shows the original floor, room boundaries, tools, and an initial section of underlayment near the far wall.",
      },
      {
        stem: "light-tile-floor-prep",
        label: "Surface preparation",
        alt: "The same wood-paneled room with underlayment fitted across the floor before tile installation",
        width: 1600,
        height: 2133,
        position: "center center",
        caption: "The preparation view shows underlayment fitted across the room before the square-format tile was installed.",
      },
    ],
    observations: [
      { title: "The same room throughout", text: "The wood paneling, double window, side window, door, wall returns, and openings match across the sequence." },
      { title: "Preparation before finish", text: "The photos move from the exposed original floor to fitted underlayment and then to the completed tile surface." },
      { title: "A clear square grid", text: "Dark joints separate light square pieces across the floor and continue toward the doorway and wall edges." },
    ],
    planning: floorPlanning,
    service: { href: "/services/tile-floor-installation/", label: "Tile floor installation service" },
    advice: { href: "/advice/preparing-for-tile-flooring-installation/", label: "Tile flooring preparation guide" },
  },
  {
    slug: "white-subway-detail",
    indexable: false,
    editorialStatus: "hold-for-facts",
    title: "Gloss White Subway Detail",
    seoTitle: "Gloss White Subway Backsplash Detail | Mr. Backsplash",
    description: "View a close backsplash detail showing gloss white rectangular tile, a wood counter, an outlet, a corner, and under-cabinet lighting.",
    summary: "A low-angle detail shows gloss white rectangular tile meeting a wood counter, inside corner, cabinet edge, outlet, and under-cabinet lights.",
    category: "Kitchen finish detail",
    stage: "Finished detail",
    image: { stem: "white-subway-detail", alt: "Close view of gloss white rectangular backsplash tile above a wood counter, beside an outlet and inside corner", width: 1600, height: 2133, position: "center 58%" },
    caption: "This close view is presented independently because the repository does not confirm which wider kitchen photo belongs with it.",
    observations: [
      { title: "A close corner view", text: "The horizontal pattern turns through an inside corner beneath the upper cabinetry." },
      { title: "A visible outlet cut", text: "The field meets an outlet plate near the left edge of the photo." },
      { title: "Light across a reflective surface", text: "Under-cabinet fixtures emphasize the uneven reflective character of the gloss finish." },
    ],
    planning: kitchenPlanning,
    service: { href: "/services/kitchen-backsplash-installation/", label: "Kitchen backsplash service" },
    advice: { href: "/advice/planning-a-kitchen-backsplash/", label: "Kitchen backsplash planning guide" },
  },
];

export const indexableProjects = projects.filter((project) => project.indexable);

export function getProject(slug) {
  return projects.find((project) => project.slug === slug);
}
